MVC_MicroService/Models/ErrorViewModel.cs
using System;

namespace MVC_MicroService.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC_MicroService/Controllers/AirportController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_MicroService.Services;

namespace MVC_MicroService.Controllers
{
    public class AirportController : Controller
    {

        private readonly FrontEndService _service;

        public AirportController(FrontEndService context)
        {
            _service = context;
        }


        public IActionResult Index()
        {
            return View(_service.Get());
        }
    }
}

MVC_MicroService/Controllers/AirportSQLController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_MicroService.Data;
using Model;

namespace MVC_MicroService.Controllers
{
    public class AirportSQLController : Controller
    {
        private readonly MVC_MicroServiceContext _context;

        public AirportSQLController(MVC_MicroServiceContext context)
        {
            _context = context;
        }

        // GET: AirportSQL
        public async Task<IActionResult> Index()
        {
            return View(await _context.Airport.ToListAsync());
        }

        // GET: AirportSQL/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var airportSQL = await _context.Airport
                .FirstOrDefaultAsync(m => m.Id == id);
            if (airportSQL == null)
            {
                return NotFound();
            }

            return View(airportSQL);
        }

        // GET: AirportSQL/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AirportSQL/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,City,Country,Code,Continent")] AirportSQL airportSQL)
        {
            if (ModelState.IsValid)
            {
                _context.Add(airportSQL);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(airportSQL);
        }

        // GET: AirportSQL/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var airportSQL = await _context.Airport.FindAsync(id);
            if (airportSQL == null)
            {
                return NotFound();
            }
            return View(airportSQL);
        }

        // POST: AirportSQL/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,City,Country,Code,Continent")] AirportSQL airportSQL)
        {
            if (id != airportSQL.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(airportSQL);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AirportSQLExists(airportSQL.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(airportSQL);
        }

        // GET: AirportSQL/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var airportSQL = await _context.Airport
                .FirstOrDefaultAsync(m => m.Id == id);
            if (airportSQL == null)
            {
                return NotFound();
            }

            return View(airportSQL);
        }

        // POST: AirportSQL/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var airportSQL = await _context.Airport.FindAsync(id);
            _context.Airport.Remove(airportSQL);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AirportSQLExists(int id)
        {
            return _context.Airport.Any(e => e.Id == id);
        }
    }
}

MVC_MicroService/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC_MicroService.Models;

namespace MVC_MicroService.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC_MicroService/Views/Airport/Create.cshtml
@model Model.Airport

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Airport</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IATA_Code" class="control-label"></label>
                <input asp-for="IATA_Code" class="form-control" />
                <span asp-validation-for="IATA_Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Airport_Name" class="control-label"></label>
                <input asp-for="Airport_Name" class="form-control" />
                <span asp-validation-for="Airport_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserLogin" class="control-label"></label>
                <input asp-for="UserLogin" class="form-control" />
                <span asp-validation-for="UserLogin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_MicroService/Views/Airport/Delete.cshtml
@model Model.Airport

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Airport</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IATA_Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IATA_Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Airport_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Airport_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserLogin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserLogin)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC_MicroService/Views/Airport/Details.cshtml
@model Model.Airport

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Airport</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IATA_Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IATA_Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Airport_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Airport_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserLogin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserLogin)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVC_MicroService/Views/Airport/Edit.cshtml
@model Model.Airport

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Airport</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="IATA_Code" class="control-label"></label>
                <input asp-for="IATA_Code" class="form-control" />
                <span asp-validation-for="IATA_Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Airport_Name" class="control-label"></label>
                <input asp-for="Airport_Name" class="form-control" />
                <span asp-validation-for="Airport_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserLogin" class="control-label"></label>
                <input asp-for="UserLogin" class="form-control" />
                <span asp-validation-for="UserLogin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_MicroService/Views/Airport/Index.cshtml
@model IEnumerable<Model.Airport>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IATA_Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Airport_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserLogin)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IATA_Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Airport_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserLogin)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MVC_MicroService/Views/AirportSQL/Create.cshtml
@model Model.AirportSQL

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>AirportSQL</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Continent" class="control-label"></label>
                <input asp-for="Continent" class="form-control" />
                <span asp-validation-for="Continent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_MicroService/Views/AirportSQL/Delete.cshtml
@model Model.AirportSQL

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AirportSQL</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Continent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Continent)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC_MicroService/Views/AirportSQL/Details.cshtml
@model Model.AirportSQL

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>AirportSQL</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Continent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Continent)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVC_MicroService/Views/AirportSQL/Edit.cshtml
@model Model.AirportSQL

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>AirportSQL</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Continent" class="control-label"></label>
                <input asp-for="Continent" class="form-control" />
                <span asp-validation-for="Continent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_MicroService/Views/AirportSQL/Index.cshtml
@model IEnumerable<Model.AirportSQL>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Continent)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Continent)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MVC_MicroService/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC_MicroService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_MicroService</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_MicroService</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                                                <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AirportSQL" asp-action="Index">AirportSQL</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Airport" asp-action="Index">Airport</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC_MicroService - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>